#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀🚀🚀 Starting pre-push scripts 🚀🚀🚀";
echo "🐺🐺🐺 Ohh, you already know me right?";
echo "";

echo "1 - 💅👀🤌 It's time to check the format of your code!";

yarn check:format ||
(
    echo "🥴😵‍💫🥴😵‍💫 So you're someone who likes to mess things up right? 🥴😵‍💫🥴😵‍💫";
    echo "Check Format failed, run 'yarn check-format' to try again";

    false;
)

echo "";
echo "🤔🤔🤔... Right... Right... Congratulations on the minimum";

echo "";
echo "|-------------------------------------------------------------------------|";
echo "";

echo "2 - 📖👀🤌 I called Phoenix Wright to check the rules, it's time to check the lint!";

yarn check:lint ||
(
    echo "😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤";
    echo "ESLint Check failed, run 'yarn check-lint' to try again";

    false;
)

echo "";
echo "🤔🤔🤔... So your code looks great? Let's see if anyone learned OO";

echo "";
echo "|-------------------------------------------------------------------------|";
echo "";

echo "3 - 🪧👀🤌 I'm not your type? Well, it's time to check the types!";
echo ""

yarn check:types ||
(
    echo "🤡😂❌🤡 You're not dumb, you're just... hmmm... quirky right? 🤡😂❌🤡";
    echo "Types Check failed, run 'yarn check-types' to try again";

    false;
)

echo "";
echo "🥳🥳🥳 Your effort brought you this far, It's push time!!! 🥳🥳🥳";
echo "";
